# Copyright (c) 2023 Cisco Systems, Inc. and its affiliates
# All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http:www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

# Traffic Type 
  # API Services
  # Artificial Intelligence (AI) Applications
  # Augmented Reality (AR)
  # Backup and Recovery Systems
  # Big Data Processing
  # Blockchain Transactions
  # Business Intelligence Tools
  # Business Process Management (BPM)
  # Collaboration Tools
  # Content Delivery Networks (CDN)
  # Content Management Systems (CMS)
  # CRM Software
  # Customer Relationship Management (CRM)
  # Database Systems
  # Document Management Systems
  # Email Servers
  # Engineering
  # Enterprise Asset Management (EAM)
  # Enterprise Resource Planning (ERP)
  # ERP Systems
  # File Sharing and Storage
  # Financial Services
  # Generic
  # Human Resources Management (HRM)
  # Identity and Access Management
  # Intranet and Internal Web Applications
  # Internet of Things (IoT) Devices
  # Learning Management Systems (LMS)
  # Machine Learning (ML) Training
  # Messaging Services
  # Mixed Reality (MR)
  # Network Management and Monitoring
  # Product Lifecycle Management (PLM)
  # Project Management
  # Real-time Analytics
  # Security Services
  # Service Mesh
  # Software Development and Version Control
  # Streaming Services
  # Supply Chain Management (SCM)
  # Virtual Meeting Platforms
  # Virtual Private Network (VPN)
  # Virtual Reality (VR)
  # Video Streaming Services
  # VoIP Systems

apiVersion: awi.app-net-interface.io/v1alpha
kind: TrafficPolicy #A network domain could be a VPC or VRF. Exists behind a router.
metadata:
  name: "inter-network-domain-policy-1"
  namespace: "Policy to connect networks"
spec:
  metadata:
    name : ""
    description: ""
    creationTimestamp: "2023-08-15T12:34:56Z"
    modificationTimestamp: "2023-08-15T13:45:67Z"
    category: "Regular" #Business Critical | Mission critical | Essential | Regular | Strategic | Compliance | Customer-Facing | Operational | Support
    trafficType: ""  
  trafficSLO: 
    priority: 0 # Between 0 to 10
    QoSParams: 
      bandwidth: 20 # Mbps
      jitter: 5 # 5 milisecond
      latency: 60 # latency shouldn't exceed <<latency>> miliseconds
      loss: 0.5 # Packet loss percentage that's acceptable for this application
    enforcementRequest:
      type: "hard" # Hard or soft (best effort)
