// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeAppConnectionControllerServer is an autogenerated mock type for the UnsafeAppConnectionControllerServer type
type UnsafeAppConnectionControllerServer struct {
	mock.Mock
}

type UnsafeAppConnectionControllerServer_Expecter struct {
	mock *mock.Mock
}

func (_m *UnsafeAppConnectionControllerServer) EXPECT() *UnsafeAppConnectionControllerServer_Expecter {
	return &UnsafeAppConnectionControllerServer_Expecter{mock: &_m.Mock}
}

// mustEmbedUnimplementedAppConnectionControllerServer provides a mock function with given fields:
func (_m *UnsafeAppConnectionControllerServer) mustEmbedUnimplementedAppConnectionControllerServer() {
	_m.Called()
}

// UnsafeAppConnectionControllerServer_mustEmbedUnimplementedAppConnectionControllerServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedAppConnectionControllerServer'
type UnsafeAppConnectionControllerServer_mustEmbedUnimplementedAppConnectionControllerServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedAppConnectionControllerServer is a helper method to define mock.On call
func (_e *UnsafeAppConnectionControllerServer_Expecter) mustEmbedUnimplementedAppConnectionControllerServer() *UnsafeAppConnectionControllerServer_mustEmbedUnimplementedAppConnectionControllerServer_Call {
	return &UnsafeAppConnectionControllerServer_mustEmbedUnimplementedAppConnectionControllerServer_Call{Call: _e.mock.On("mustEmbedUnimplementedAppConnectionControllerServer")}
}

func (_c *UnsafeAppConnectionControllerServer_mustEmbedUnimplementedAppConnectionControllerServer_Call) Run(run func()) *UnsafeAppConnectionControllerServer_mustEmbedUnimplementedAppConnectionControllerServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UnsafeAppConnectionControllerServer_mustEmbedUnimplementedAppConnectionControllerServer_Call) Return() *UnsafeAppConnectionControllerServer_mustEmbedUnimplementedAppConnectionControllerServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *UnsafeAppConnectionControllerServer_mustEmbedUnimplementedAppConnectionControllerServer_Call) RunAndReturn(run func()) *UnsafeAppConnectionControllerServer_mustEmbedUnimplementedAppConnectionControllerServer_Call {
	_c.Call.Return(run)
	return _c
}

// NewUnsafeAppConnectionControllerServer creates a new instance of UnsafeAppConnectionControllerServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeAppConnectionControllerServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeAppConnectionControllerServer {
	mock := &UnsafeAppConnectionControllerServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
