// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeSecurityPolicyServiceServer is an autogenerated mock type for the UnsafeSecurityPolicyServiceServer type
type UnsafeSecurityPolicyServiceServer struct {
	mock.Mock
}

type UnsafeSecurityPolicyServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *UnsafeSecurityPolicyServiceServer) EXPECT() *UnsafeSecurityPolicyServiceServer_Expecter {
	return &UnsafeSecurityPolicyServiceServer_Expecter{mock: &_m.Mock}
}

// mustEmbedUnimplementedSecurityPolicyServiceServer provides a mock function with given fields:
func (_m *UnsafeSecurityPolicyServiceServer) mustEmbedUnimplementedSecurityPolicyServiceServer() {
	_m.Called()
}

// UnsafeSecurityPolicyServiceServer_mustEmbedUnimplementedSecurityPolicyServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedSecurityPolicyServiceServer'
type UnsafeSecurityPolicyServiceServer_mustEmbedUnimplementedSecurityPolicyServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedSecurityPolicyServiceServer is a helper method to define mock.On call
func (_e *UnsafeSecurityPolicyServiceServer_Expecter) mustEmbedUnimplementedSecurityPolicyServiceServer() *UnsafeSecurityPolicyServiceServer_mustEmbedUnimplementedSecurityPolicyServiceServer_Call {
	return &UnsafeSecurityPolicyServiceServer_mustEmbedUnimplementedSecurityPolicyServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedSecurityPolicyServiceServer")}
}

func (_c *UnsafeSecurityPolicyServiceServer_mustEmbedUnimplementedSecurityPolicyServiceServer_Call) Run(run func()) *UnsafeSecurityPolicyServiceServer_mustEmbedUnimplementedSecurityPolicyServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UnsafeSecurityPolicyServiceServer_mustEmbedUnimplementedSecurityPolicyServiceServer_Call) Return() *UnsafeSecurityPolicyServiceServer_mustEmbedUnimplementedSecurityPolicyServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *UnsafeSecurityPolicyServiceServer_mustEmbedUnimplementedSecurityPolicyServiceServer_Call) RunAndReturn(run func()) *UnsafeSecurityPolicyServiceServer_mustEmbedUnimplementedSecurityPolicyServiceServer_Call {
	_c.Call.Return(run)
	return _c
}

// NewUnsafeSecurityPolicyServiceServer creates a new instance of UnsafeSecurityPolicyServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeSecurityPolicyServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeSecurityPolicyServiceServer {
	mock := &UnsafeSecurityPolicyServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
