// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeCloudServer is an autogenerated mock type for the UnsafeCloudServer type
type UnsafeCloudServer struct {
	mock.Mock
}

type UnsafeCloudServer_Expecter struct {
	mock *mock.Mock
}

func (_m *UnsafeCloudServer) EXPECT() *UnsafeCloudServer_Expecter {
	return &UnsafeCloudServer_Expecter{mock: &_m.Mock}
}

// mustEmbedUnimplementedCloudServer provides a mock function with given fields:
func (_m *UnsafeCloudServer) mustEmbedUnimplementedCloudServer() {
	_m.Called()
}

// UnsafeCloudServer_mustEmbedUnimplementedCloudServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedCloudServer'
type UnsafeCloudServer_mustEmbedUnimplementedCloudServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedCloudServer is a helper method to define mock.On call
func (_e *UnsafeCloudServer_Expecter) mustEmbedUnimplementedCloudServer() *UnsafeCloudServer_mustEmbedUnimplementedCloudServer_Call {
	return &UnsafeCloudServer_mustEmbedUnimplementedCloudServer_Call{Call: _e.mock.On("mustEmbedUnimplementedCloudServer")}
}

func (_c *UnsafeCloudServer_mustEmbedUnimplementedCloudServer_Call) Run(run func()) *UnsafeCloudServer_mustEmbedUnimplementedCloudServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UnsafeCloudServer_mustEmbedUnimplementedCloudServer_Call) Return() *UnsafeCloudServer_mustEmbedUnimplementedCloudServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *UnsafeCloudServer_mustEmbedUnimplementedCloudServer_Call) RunAndReturn(run func()) *UnsafeCloudServer_mustEmbedUnimplementedCloudServer_Call {
	_c.Call.Return(run)
	return _c
}

// NewUnsafeCloudServer creates a new instance of UnsafeCloudServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeCloudServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeCloudServer {
	mock := &UnsafeCloudServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
