// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeNetworkSLAServiceServer is an autogenerated mock type for the UnsafeNetworkSLAServiceServer type
type UnsafeNetworkSLAServiceServer struct {
	mock.Mock
}

type UnsafeNetworkSLAServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *UnsafeNetworkSLAServiceServer) EXPECT() *UnsafeNetworkSLAServiceServer_Expecter {
	return &UnsafeNetworkSLAServiceServer_Expecter{mock: &_m.Mock}
}

// mustEmbedUnimplementedNetworkSLAServiceServer provides a mock function with given fields:
func (_m *UnsafeNetworkSLAServiceServer) mustEmbedUnimplementedNetworkSLAServiceServer() {
	_m.Called()
}

// UnsafeNetworkSLAServiceServer_mustEmbedUnimplementedNetworkSLAServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedNetworkSLAServiceServer'
type UnsafeNetworkSLAServiceServer_mustEmbedUnimplementedNetworkSLAServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedNetworkSLAServiceServer is a helper method to define mock.On call
func (_e *UnsafeNetworkSLAServiceServer_Expecter) mustEmbedUnimplementedNetworkSLAServiceServer() *UnsafeNetworkSLAServiceServer_mustEmbedUnimplementedNetworkSLAServiceServer_Call {
	return &UnsafeNetworkSLAServiceServer_mustEmbedUnimplementedNetworkSLAServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedNetworkSLAServiceServer")}
}

func (_c *UnsafeNetworkSLAServiceServer_mustEmbedUnimplementedNetworkSLAServiceServer_Call) Run(run func()) *UnsafeNetworkSLAServiceServer_mustEmbedUnimplementedNetworkSLAServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UnsafeNetworkSLAServiceServer_mustEmbedUnimplementedNetworkSLAServiceServer_Call) Return() *UnsafeNetworkSLAServiceServer_mustEmbedUnimplementedNetworkSLAServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *UnsafeNetworkSLAServiceServer_mustEmbedUnimplementedNetworkSLAServiceServer_Call) RunAndReturn(run func()) *UnsafeNetworkSLAServiceServer_mustEmbedUnimplementedNetworkSLAServiceServer_Call {
	_c.Call.Return(run)
	return _c
}

// NewUnsafeNetworkSLAServiceServer creates a new instance of UnsafeNetworkSLAServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeNetworkSLAServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeNetworkSLAServiceServer {
	mock := &UnsafeNetworkSLAServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
