// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package awi

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using AppConnection within kubernetes types, where deepcopy-gen is used.
func (in *AppConnection) DeepCopyInto(out *AppConnection) {
	p := proto.Clone(in).(*AppConnection)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppConnection. Required by controller-gen.
func (in *AppConnection) DeepCopy() *AppConnection {
	if in == nil {
		return nil
	}
	out := new(AppConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AppConnection. Required by controller-gen.
func (in *AppConnection) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AppMetadata within kubernetes types, where deepcopy-gen is used.
func (in *AppMetadata) DeepCopyInto(out *AppMetadata) {
	p := proto.Clone(in).(*AppMetadata)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppMetadata. Required by controller-gen.
func (in *AppMetadata) DeepCopy() *AppMetadata {
	if in == nil {
		return nil
	}
	out := new(AppMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AppMetadata. Required by controller-gen.
func (in *AppMetadata) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using From within kubernetes types, where deepcopy-gen is used.
func (in *From) DeepCopyInto(out *From) {
	p := proto.Clone(in).(*From)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new From. Required by controller-gen.
func (in *From) DeepCopy() *From {
	if in == nil {
		return nil
	}
	out := new(From)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new From. Required by controller-gen.
func (in *From) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using To within kubernetes types, where deepcopy-gen is used.
func (in *To) DeepCopyInto(out *To) {
	p := proto.Clone(in).(*To)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new To. Required by controller-gen.
func (in *To) DeepCopy() *To {
	if in == nil {
		return nil
	}
	out := new(To)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new To. Required by controller-gen.
func (in *To) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using MatchName within kubernetes types, where deepcopy-gen is used.
func (in *MatchName) DeepCopyInto(out *MatchName) {
	p := proto.Clone(in).(*MatchName)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchName. Required by controller-gen.
func (in *MatchName) DeepCopy() *MatchName {
	if in == nil {
		return nil
	}
	out := new(MatchName)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new MatchName. Required by controller-gen.
func (in *MatchName) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using MatchNamespace within kubernetes types, where deepcopy-gen is used.
func (in *MatchNamespace) DeepCopyInto(out *MatchNamespace) {
	p := proto.Clone(in).(*MatchNamespace)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchNamespace. Required by controller-gen.
func (in *MatchNamespace) DeepCopy() *MatchNamespace {
	if in == nil {
		return nil
	}
	out := new(MatchNamespace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new MatchNamespace. Required by controller-gen.
func (in *MatchNamespace) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using MatchCluster within kubernetes types, where deepcopy-gen is used.
func (in *MatchCluster) DeepCopyInto(out *MatchCluster) {
	p := proto.Clone(in).(*MatchCluster)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchCluster. Required by controller-gen.
func (in *MatchCluster) DeepCopy() *MatchCluster {
	if in == nil {
		return nil
	}
	out := new(MatchCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new MatchCluster. Required by controller-gen.
func (in *MatchCluster) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using MatchId within kubernetes types, where deepcopy-gen is used.
func (in *MatchId) DeepCopyInto(out *MatchId) {
	p := proto.Clone(in).(*MatchId)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchId. Required by controller-gen.
func (in *MatchId) DeepCopy() *MatchId {
	if in == nil {
		return nil
	}
	out := new(MatchId)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new MatchId. Required by controller-gen.
func (in *MatchId) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using MatchOwner within kubernetes types, where deepcopy-gen is used.
func (in *MatchOwner) DeepCopyInto(out *MatchOwner) {
	p := proto.Clone(in).(*MatchOwner)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchOwner. Required by controller-gen.
func (in *MatchOwner) DeepCopy() *MatchOwner {
	if in == nil {
		return nil
	}
	out := new(MatchOwner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new MatchOwner. Required by controller-gen.
func (in *MatchOwner) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using MatchHost within kubernetes types, where deepcopy-gen is used.
func (in *MatchHost) DeepCopyInto(out *MatchHost) {
	p := proto.Clone(in).(*MatchHost)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchHost. Required by controller-gen.
func (in *MatchHost) DeepCopy() *MatchHost {
	if in == nil {
		return nil
	}
	out := new(MatchHost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new MatchHost. Required by controller-gen.
func (in *MatchHost) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Endpoint within kubernetes types, where deepcopy-gen is used.
func (in *Endpoint) DeepCopyInto(out *Endpoint) {
	p := proto.Clone(in).(*Endpoint)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Endpoint. Required by controller-gen.
func (in *Endpoint) DeepCopy() *Endpoint {
	if in == nil {
		return nil
	}
	out := new(Endpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Endpoint. Required by controller-gen.
func (in *Endpoint) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Endpoint_Selector within kubernetes types, where deepcopy-gen is used.
func (in *Endpoint_Selector) DeepCopyInto(out *Endpoint_Selector) {
	p := proto.Clone(in).(*Endpoint_Selector)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Endpoint_Selector. Required by controller-gen.
func (in *Endpoint_Selector) DeepCopy() *Endpoint_Selector {
	if in == nil {
		return nil
	}
	out := new(Endpoint_Selector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Endpoint_Selector. Required by controller-gen.
func (in *Endpoint_Selector) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using MatchExpression within kubernetes types, where deepcopy-gen is used.
func (in *MatchExpression) DeepCopyInto(out *MatchExpression) {
	p := proto.Clone(in).(*MatchExpression)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchExpression. Required by controller-gen.
func (in *MatchExpression) DeepCopy() *MatchExpression {
	if in == nil {
		return nil
	}
	out := new(MatchExpression)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new MatchExpression. Required by controller-gen.
func (in *MatchExpression) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AppSubnet within kubernetes types, where deepcopy-gen is used.
func (in *AppSubnet) DeepCopyInto(out *AppSubnet) {
	p := proto.Clone(in).(*AppSubnet)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppSubnet. Required by controller-gen.
func (in *AppSubnet) DeepCopy() *AppSubnet {
	if in == nil {
		return nil
	}
	out := new(AppSubnet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AppSubnet. Required by controller-gen.
func (in *AppSubnet) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AppSubnet_Selector within kubernetes types, where deepcopy-gen is used.
func (in *AppSubnet_Selector) DeepCopyInto(out *AppSubnet_Selector) {
	p := proto.Clone(in).(*AppSubnet_Selector)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppSubnet_Selector. Required by controller-gen.
func (in *AppSubnet_Selector) DeepCopy() *AppSubnet_Selector {
	if in == nil {
		return nil
	}
	out := new(AppSubnet_Selector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AppSubnet_Selector. Required by controller-gen.
func (in *AppSubnet_Selector) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Namespace within kubernetes types, where deepcopy-gen is used.
func (in *Namespace) DeepCopyInto(out *Namespace) {
	p := proto.Clone(in).(*Namespace)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Namespace. Required by controller-gen.
func (in *Namespace) DeepCopy() *Namespace {
	if in == nil {
		return nil
	}
	out := new(Namespace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Namespace. Required by controller-gen.
func (in *Namespace) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Namespace_Selector within kubernetes types, where deepcopy-gen is used.
func (in *Namespace_Selector) DeepCopyInto(out *Namespace_Selector) {
	p := proto.Clone(in).(*Namespace_Selector)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Namespace_Selector. Required by controller-gen.
func (in *Namespace_Selector) DeepCopy() *Namespace_Selector {
	if in == nil {
		return nil
	}
	out := new(Namespace_Selector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Namespace_Selector. Required by controller-gen.
func (in *Namespace_Selector) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using SGT within kubernetes types, where deepcopy-gen is used.
func (in *SGT) DeepCopyInto(out *SGT) {
	p := proto.Clone(in).(*SGT)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGT. Required by controller-gen.
func (in *SGT) DeepCopy() *SGT {
	if in == nil {
		return nil
	}
	out := new(SGT)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new SGT. Required by controller-gen.
func (in *SGT) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ServiceKind within kubernetes types, where deepcopy-gen is used.
func (in *ServiceKind) DeepCopyInto(out *ServiceKind) {
	p := proto.Clone(in).(*ServiceKind)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceKind. Required by controller-gen.
func (in *ServiceKind) DeepCopy() *ServiceKind {
	if in == nil {
		return nil
	}
	out := new(ServiceKind)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ServiceKind. Required by controller-gen.
func (in *ServiceKind) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ServiceKind_K8SService within kubernetes types, where deepcopy-gen is used.
func (in *ServiceKind_K8SService) DeepCopyInto(out *ServiceKind_K8SService) {
	p := proto.Clone(in).(*ServiceKind_K8SService)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceKind_K8SService. Required by controller-gen.
func (in *ServiceKind_K8SService) DeepCopy() *ServiceKind_K8SService {
	if in == nil {
		return nil
	}
	out := new(ServiceKind_K8SService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ServiceKind_K8SService. Required by controller-gen.
func (in *ServiceKind_K8SService) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ServiceKind_VMService within kubernetes types, where deepcopy-gen is used.
func (in *ServiceKind_VMService) DeepCopyInto(out *ServiceKind_VMService) {
	p := proto.Clone(in).(*ServiceKind_VMService)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceKind_VMService. Required by controller-gen.
func (in *ServiceKind_VMService) DeepCopy() *ServiceKind_VMService {
	if in == nil {
		return nil
	}
	out := new(ServiceKind_VMService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ServiceKind_VMService. Required by controller-gen.
func (in *ServiceKind_VMService) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Service within kubernetes types, where deepcopy-gen is used.
func (in *Service) DeepCopyInto(out *Service) {
	p := proto.Clone(in).(*Service)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Service. Required by controller-gen.
func (in *Service) DeepCopy() *Service {
	if in == nil {
		return nil
	}
	out := new(Service)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Service. Required by controller-gen.
func (in *Service) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Service_Selector within kubernetes types, where deepcopy-gen is used.
func (in *Service_Selector) DeepCopyInto(out *Service_Selector) {
	p := proto.Clone(in).(*Service_Selector)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Service_Selector. Required by controller-gen.
func (in *Service_Selector) DeepCopy() *Service_Selector {
	if in == nil {
		return nil
	}
	out := new(Service_Selector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Service_Selector. Required by controller-gen.
func (in *Service_Selector) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Cluster within kubernetes types, where deepcopy-gen is used.
func (in *Cluster) DeepCopyInto(out *Cluster) {
	p := proto.Clone(in).(*Cluster)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cluster. Required by controller-gen.
func (in *Cluster) DeepCopy() *Cluster {
	if in == nil {
		return nil
	}
	out := new(Cluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Cluster. Required by controller-gen.
func (in *Cluster) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Cluster_Selector within kubernetes types, where deepcopy-gen is used.
func (in *Cluster_Selector) DeepCopyInto(out *Cluster_Selector) {
	p := proto.Clone(in).(*Cluster_Selector)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cluster_Selector. Required by controller-gen.
func (in *Cluster_Selector) DeepCopy() *Cluster_Selector {
	if in == nil {
		return nil
	}
	out := new(Cluster_Selector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Cluster_Selector. Required by controller-gen.
func (in *Cluster_Selector) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using NetworkDomain within kubernetes types, where deepcopy-gen is used.
func (in *NetworkDomain) DeepCopyInto(out *NetworkDomain) {
	p := proto.Clone(in).(*NetworkDomain)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDomain. Required by controller-gen.
func (in *NetworkDomain) DeepCopy() *NetworkDomain {
	if in == nil {
		return nil
	}
	out := new(NetworkDomain)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDomain. Required by controller-gen.
func (in *NetworkDomain) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using NetworkDomain_Selector within kubernetes types, where deepcopy-gen is used.
func (in *NetworkDomain_Selector) DeepCopyInto(out *NetworkDomain_Selector) {
	p := proto.Clone(in).(*NetworkDomain_Selector)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDomain_Selector. Required by controller-gen.
func (in *NetworkDomain_Selector) DeepCopy() *NetworkDomain_Selector {
	if in == nil {
		return nil
	}
	out := new(NetworkDomain_Selector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDomain_Selector. Required by controller-gen.
func (in *NetworkDomain_Selector) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AccessPolicySelector within kubernetes types, where deepcopy-gen is used.
func (in *AccessPolicySelector) DeepCopyInto(out *AccessPolicySelector) {
	p := proto.Clone(in).(*AccessPolicySelector)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessPolicySelector. Required by controller-gen.
func (in *AccessPolicySelector) DeepCopy() *AccessPolicySelector {
	if in == nil {
		return nil
	}
	out := new(AccessPolicySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AccessPolicySelector. Required by controller-gen.
func (in *AccessPolicySelector) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AccessPolicySelector_Selector within kubernetes types, where deepcopy-gen is used.
func (in *AccessPolicySelector_Selector) DeepCopyInto(out *AccessPolicySelector_Selector) {
	p := proto.Clone(in).(*AccessPolicySelector_Selector)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessPolicySelector_Selector. Required by controller-gen.
func (in *AccessPolicySelector_Selector) DeepCopy() *AccessPolicySelector_Selector {
	if in == nil {
		return nil
	}
	out := new(AccessPolicySelector_Selector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AccessPolicySelector_Selector. Required by controller-gen.
func (in *AccessPolicySelector_Selector) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AccessPolicySelector_MatchName within kubernetes types, where deepcopy-gen is used.
func (in *AccessPolicySelector_MatchName) DeepCopyInto(out *AccessPolicySelector_MatchName) {
	p := proto.Clone(in).(*AccessPolicySelector_MatchName)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessPolicySelector_MatchName. Required by controller-gen.
func (in *AccessPolicySelector_MatchName) DeepCopy() *AccessPolicySelector_MatchName {
	if in == nil {
		return nil
	}
	out := new(AccessPolicySelector_MatchName)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AccessPolicySelector_MatchName. Required by controller-gen.
func (in *AccessPolicySelector_MatchName) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AccessPolicySelector_MatchId within kubernetes types, where deepcopy-gen is used.
func (in *AccessPolicySelector_MatchId) DeepCopyInto(out *AccessPolicySelector_MatchId) {
	p := proto.Clone(in).(*AccessPolicySelector_MatchId)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessPolicySelector_MatchId. Required by controller-gen.
func (in *AccessPolicySelector_MatchId) DeepCopy() *AccessPolicySelector_MatchId {
	if in == nil {
		return nil
	}
	out := new(AccessPolicySelector_MatchId)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AccessPolicySelector_MatchId. Required by controller-gen.
func (in *AccessPolicySelector_MatchId) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using NetworkPolicySelector within kubernetes types, where deepcopy-gen is used.
func (in *NetworkPolicySelector) DeepCopyInto(out *NetworkPolicySelector) {
	p := proto.Clone(in).(*NetworkPolicySelector)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPolicySelector. Required by controller-gen.
func (in *NetworkPolicySelector) DeepCopy() *NetworkPolicySelector {
	if in == nil {
		return nil
	}
	out := new(NetworkPolicySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPolicySelector. Required by controller-gen.
func (in *NetworkPolicySelector) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using NetworkPolicySelector_Selector within kubernetes types, where deepcopy-gen is used.
func (in *NetworkPolicySelector_Selector) DeepCopyInto(out *NetworkPolicySelector_Selector) {
	p := proto.Clone(in).(*NetworkPolicySelector_Selector)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPolicySelector_Selector. Required by controller-gen.
func (in *NetworkPolicySelector_Selector) DeepCopy() *NetworkPolicySelector_Selector {
	if in == nil {
		return nil
	}
	out := new(NetworkPolicySelector_Selector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPolicySelector_Selector. Required by controller-gen.
func (in *NetworkPolicySelector_Selector) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using NetworkAccessControl within kubernetes types, where deepcopy-gen is used.
func (in *NetworkAccessControl) DeepCopyInto(out *NetworkAccessControl) {
	p := proto.Clone(in).(*NetworkAccessControl)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkAccessControl. Required by controller-gen.
func (in *NetworkAccessControl) DeepCopy() *NetworkAccessControl {
	if in == nil {
		return nil
	}
	out := new(NetworkAccessControl)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new NetworkAccessControl. Required by controller-gen.
func (in *NetworkAccessControl) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using NetworkDomainConnection within kubernetes types, where deepcopy-gen is used.
func (in *NetworkDomainConnection) DeepCopyInto(out *NetworkDomainConnection) {
	p := proto.Clone(in).(*NetworkDomainConnection)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDomainConnection. Required by controller-gen.
func (in *NetworkDomainConnection) DeepCopy() *NetworkDomainConnection {
	if in == nil {
		return nil
	}
	out := new(NetworkDomainConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDomainConnection. Required by controller-gen.
func (in *NetworkDomainConnection) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using NetworkDomainConnection_Selector within kubernetes types, where deepcopy-gen is used.
func (in *NetworkDomainConnection_Selector) DeepCopyInto(out *NetworkDomainConnection_Selector) {
	p := proto.Clone(in).(*NetworkDomainConnection_Selector)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDomainConnection_Selector. Required by controller-gen.
func (in *NetworkDomainConnection_Selector) DeepCopy() *NetworkDomainConnection_Selector {
	if in == nil {
		return nil
	}
	out := new(NetworkDomainConnection_Selector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDomainConnection_Selector. Required by controller-gen.
func (in *NetworkDomainConnection_Selector) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using NetworkPolicy within kubernetes types, where deepcopy-gen is used.
func (in *NetworkPolicy) DeepCopyInto(out *NetworkPolicy) {
	p := proto.Clone(in).(*NetworkPolicy)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPolicy. Required by controller-gen.
func (in *NetworkPolicy) DeepCopy() *NetworkPolicy {
	if in == nil {
		return nil
	}
	out := new(NetworkPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPolicy. Required by controller-gen.
func (in *NetworkPolicy) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using NetworkPolicy_Selector within kubernetes types, where deepcopy-gen is used.
func (in *NetworkPolicy_Selector) DeepCopyInto(out *NetworkPolicy_Selector) {
	p := proto.Clone(in).(*NetworkPolicy_Selector)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPolicy_Selector. Required by controller-gen.
func (in *NetworkPolicy_Selector) DeepCopy() *NetworkPolicy_Selector {
	if in == nil {
		return nil
	}
	out := new(NetworkPolicy_Selector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPolicy_Selector. Required by controller-gen.
func (in *NetworkPolicy_Selector) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AppConnectionResponse within kubernetes types, where deepcopy-gen is used.
func (in *AppConnectionResponse) DeepCopyInto(out *AppConnectionResponse) {
	p := proto.Clone(in).(*AppConnectionResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppConnectionResponse. Required by controller-gen.
func (in *AppConnectionResponse) DeepCopy() *AppConnectionResponse {
	if in == nil {
		return nil
	}
	out := new(AppConnectionResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AppConnectionResponse. Required by controller-gen.
func (in *AppConnectionResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AppConnectionResponseMeta within kubernetes types, where deepcopy-gen is used.
func (in *AppConnectionResponseMeta) DeepCopyInto(out *AppConnectionResponseMeta) {
	p := proto.Clone(in).(*AppConnectionResponseMeta)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppConnectionResponseMeta. Required by controller-gen.
func (in *AppConnectionResponseMeta) DeepCopy() *AppConnectionResponseMeta {
	if in == nil {
		return nil
	}
	out := new(AppConnectionResponseMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AppConnectionResponseMeta. Required by controller-gen.
func (in *AppConnectionResponseMeta) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetAppConnectionResponse within kubernetes types, where deepcopy-gen is used.
func (in *GetAppConnectionResponse) DeepCopyInto(out *GetAppConnectionResponse) {
	p := proto.Clone(in).(*GetAppConnectionResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetAppConnectionResponse. Required by controller-gen.
func (in *GetAppConnectionResponse) DeepCopy() *GetAppConnectionResponse {
	if in == nil {
		return nil
	}
	out := new(GetAppConnectionResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetAppConnectionResponse. Required by controller-gen.
func (in *GetAppConnectionResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AppDisconnectionRequest within kubernetes types, where deepcopy-gen is used.
func (in *AppDisconnectionRequest) DeepCopyInto(out *AppDisconnectionRequest) {
	p := proto.Clone(in).(*AppDisconnectionRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppDisconnectionRequest. Required by controller-gen.
func (in *AppDisconnectionRequest) DeepCopy() *AppDisconnectionRequest {
	if in == nil {
		return nil
	}
	out := new(AppDisconnectionRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AppDisconnectionRequest. Required by controller-gen.
func (in *AppDisconnectionRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AppDisconnectionResponse within kubernetes types, where deepcopy-gen is used.
func (in *AppDisconnectionResponse) DeepCopyInto(out *AppDisconnectionResponse) {
	p := proto.Clone(in).(*AppDisconnectionResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppDisconnectionResponse. Required by controller-gen.
func (in *AppDisconnectionResponse) DeepCopy() *AppDisconnectionResponse {
	if in == nil {
		return nil
	}
	out := new(AppDisconnectionResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AppDisconnectionResponse. Required by controller-gen.
func (in *AppDisconnectionResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AppConnectionStatusResponse within kubernetes types, where deepcopy-gen is used.
func (in *AppConnectionStatusResponse) DeepCopyInto(out *AppConnectionStatusResponse) {
	p := proto.Clone(in).(*AppConnectionStatusResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppConnectionStatusResponse. Required by controller-gen.
func (in *AppConnectionStatusResponse) DeepCopy() *AppConnectionStatusResponse {
	if in == nil {
		return nil
	}
	out := new(AppConnectionStatusResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AppConnectionStatusResponse. Required by controller-gen.
func (in *AppConnectionStatusResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AppConnectionStatistics within kubernetes types, where deepcopy-gen is used.
func (in *AppConnectionStatistics) DeepCopyInto(out *AppConnectionStatistics) {
	p := proto.Clone(in).(*AppConnectionStatistics)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppConnectionStatistics. Required by controller-gen.
func (in *AppConnectionStatistics) DeepCopy() *AppConnectionStatistics {
	if in == nil {
		return nil
	}
	out := new(AppConnectionStatistics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AppConnectionStatistics. Required by controller-gen.
func (in *AppConnectionStatistics) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AppConnectionStatisticsResponse within kubernetes types, where deepcopy-gen is used.
func (in *AppConnectionStatisticsResponse) DeepCopyInto(out *AppConnectionStatisticsResponse) {
	p := proto.Clone(in).(*AppConnectionStatisticsResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppConnectionStatisticsResponse. Required by controller-gen.
func (in *AppConnectionStatisticsResponse) DeepCopy() *AppConnectionStatisticsResponse {
	if in == nil {
		return nil
	}
	out := new(AppConnectionStatisticsResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AppConnectionStatisticsResponse. Required by controller-gen.
func (in *AppConnectionStatisticsResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AppConnectionEvents within kubernetes types, where deepcopy-gen is used.
func (in *AppConnectionEvents) DeepCopyInto(out *AppConnectionEvents) {
	p := proto.Clone(in).(*AppConnectionEvents)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppConnectionEvents. Required by controller-gen.
func (in *AppConnectionEvents) DeepCopy() *AppConnectionEvents {
	if in == nil {
		return nil
	}
	out := new(AppConnectionEvents)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AppConnectionEvents. Required by controller-gen.
func (in *AppConnectionEvents) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AppConnectionEventsResponse within kubernetes types, where deepcopy-gen is used.
func (in *AppConnectionEventsResponse) DeepCopyInto(out *AppConnectionEventsResponse) {
	p := proto.Clone(in).(*AppConnectionEventsResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppConnectionEventsResponse. Required by controller-gen.
func (in *AppConnectionEventsResponse) DeepCopy() *AppConnectionEventsResponse {
	if in == nil {
		return nil
	}
	out := new(AppConnectionEventsResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AppConnectionEventsResponse. Required by controller-gen.
func (in *AppConnectionEventsResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetAppConnectionRequest within kubernetes types, where deepcopy-gen is used.
func (in *GetAppConnectionRequest) DeepCopyInto(out *GetAppConnectionRequest) {
	p := proto.Clone(in).(*GetAppConnectionRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetAppConnectionRequest. Required by controller-gen.
func (in *GetAppConnectionRequest) DeepCopy() *GetAppConnectionRequest {
	if in == nil {
		return nil
	}
	out := new(GetAppConnectionRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetAppConnectionRequest. Required by controller-gen.
func (in *GetAppConnectionRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetAppConnectionStatusRequest within kubernetes types, where deepcopy-gen is used.
func (in *GetAppConnectionStatusRequest) DeepCopyInto(out *GetAppConnectionStatusRequest) {
	p := proto.Clone(in).(*GetAppConnectionStatusRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetAppConnectionStatusRequest. Required by controller-gen.
func (in *GetAppConnectionStatusRequest) DeepCopy() *GetAppConnectionStatusRequest {
	if in == nil {
		return nil
	}
	out := new(GetAppConnectionStatusRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetAppConnectionStatusRequest. Required by controller-gen.
func (in *GetAppConnectionStatusRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetAppConnectionStatisticsRequest within kubernetes types, where deepcopy-gen is used.
func (in *GetAppConnectionStatisticsRequest) DeepCopyInto(out *GetAppConnectionStatisticsRequest) {
	p := proto.Clone(in).(*GetAppConnectionStatisticsRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetAppConnectionStatisticsRequest. Required by controller-gen.
func (in *GetAppConnectionStatisticsRequest) DeepCopy() *GetAppConnectionStatisticsRequest {
	if in == nil {
		return nil
	}
	out := new(GetAppConnectionStatisticsRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetAppConnectionStatisticsRequest. Required by controller-gen.
func (in *GetAppConnectionStatisticsRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetAppConnectionEventsRequest within kubernetes types, where deepcopy-gen is used.
func (in *GetAppConnectionEventsRequest) DeepCopyInto(out *GetAppConnectionEventsRequest) {
	p := proto.Clone(in).(*GetAppConnectionEventsRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetAppConnectionEventsRequest. Required by controller-gen.
func (in *GetAppConnectionEventsRequest) DeepCopy() *GetAppConnectionEventsRequest {
	if in == nil {
		return nil
	}
	out := new(GetAppConnectionEventsRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetAppConnectionEventsRequest. Required by controller-gen.
func (in *GetAppConnectionEventsRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ListAppConnectionsRequest within kubernetes types, where deepcopy-gen is used.
func (in *ListAppConnectionsRequest) DeepCopyInto(out *ListAppConnectionsRequest) {
	p := proto.Clone(in).(*ListAppConnectionsRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListAppConnectionsRequest. Required by controller-gen.
func (in *ListAppConnectionsRequest) DeepCopy() *ListAppConnectionsRequest {
	if in == nil {
		return nil
	}
	out := new(ListAppConnectionsRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ListAppConnectionsRequest. Required by controller-gen.
func (in *ListAppConnectionsRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ListAppConnectionsResponse within kubernetes types, where deepcopy-gen is used.
func (in *ListAppConnectionsResponse) DeepCopyInto(out *ListAppConnectionsResponse) {
	p := proto.Clone(in).(*ListAppConnectionsResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListAppConnectionsResponse. Required by controller-gen.
func (in *ListAppConnectionsResponse) DeepCopy() *ListAppConnectionsResponse {
	if in == nil {
		return nil
	}
	out := new(ListAppConnectionsResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ListAppConnectionsResponse. Required by controller-gen.
func (in *ListAppConnectionsResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using MatchedResources within kubernetes types, where deepcopy-gen is used.
func (in *MatchedResources) DeepCopyInto(out *MatchedResources) {
	p := proto.Clone(in).(*MatchedResources)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchedResources. Required by controller-gen.
func (in *MatchedResources) DeepCopy() *MatchedResources {
	if in == nil {
		return nil
	}
	out := new(MatchedResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new MatchedResources. Required by controller-gen.
func (in *MatchedResources) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AppConnectionInformation within kubernetes types, where deepcopy-gen is used.
func (in *AppConnectionInformation) DeepCopyInto(out *AppConnectionInformation) {
	p := proto.Clone(in).(*AppConnectionInformation)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppConnectionInformation. Required by controller-gen.
func (in *AppConnectionInformation) DeepCopy() *AppConnectionInformation {
	if in == nil {
		return nil
	}
	out := new(AppConnectionInformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AppConnectionInformation. Required by controller-gen.
func (in *AppConnectionInformation) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetMatchedResourcesResponse within kubernetes types, where deepcopy-gen is used.
func (in *GetMatchedResourcesResponse) DeepCopyInto(out *GetMatchedResourcesResponse) {
	p := proto.Clone(in).(*GetMatchedResourcesResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetMatchedResourcesResponse. Required by controller-gen.
func (in *GetMatchedResourcesResponse) DeepCopy() *GetMatchedResourcesResponse {
	if in == nil {
		return nil
	}
	out := new(GetMatchedResourcesResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetMatchedResourcesResponse. Required by controller-gen.
func (in *GetMatchedResourcesResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AppConnectionPolicy within kubernetes types, where deepcopy-gen is used.
func (in *AppConnectionPolicy) DeepCopyInto(out *AppConnectionPolicy) {
	p := proto.Clone(in).(*AppConnectionPolicy)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppConnectionPolicy. Required by controller-gen.
func (in *AppConnectionPolicy) DeepCopy() *AppConnectionPolicy {
	if in == nil {
		return nil
	}
	out := new(AppConnectionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AppConnectionPolicy. Required by controller-gen.
func (in *AppConnectionPolicy) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using CreateAppConnectionPolicyRequest within kubernetes types, where deepcopy-gen is used.
func (in *CreateAppConnectionPolicyRequest) DeepCopyInto(out *CreateAppConnectionPolicyRequest) {
	p := proto.Clone(in).(*CreateAppConnectionPolicyRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreateAppConnectionPolicyRequest. Required by controller-gen.
func (in *CreateAppConnectionPolicyRequest) DeepCopy() *CreateAppConnectionPolicyRequest {
	if in == nil {
		return nil
	}
	out := new(CreateAppConnectionPolicyRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new CreateAppConnectionPolicyRequest. Required by controller-gen.
func (in *CreateAppConnectionPolicyRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using CreateAppConnectionPolicyResponse within kubernetes types, where deepcopy-gen is used.
func (in *CreateAppConnectionPolicyResponse) DeepCopyInto(out *CreateAppConnectionPolicyResponse) {
	p := proto.Clone(in).(*CreateAppConnectionPolicyResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreateAppConnectionPolicyResponse. Required by controller-gen.
func (in *CreateAppConnectionPolicyResponse) DeepCopy() *CreateAppConnectionPolicyResponse {
	if in == nil {
		return nil
	}
	out := new(CreateAppConnectionPolicyResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new CreateAppConnectionPolicyResponse. Required by controller-gen.
func (in *CreateAppConnectionPolicyResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetAppConnectionPolicyRequest within kubernetes types, where deepcopy-gen is used.
func (in *GetAppConnectionPolicyRequest) DeepCopyInto(out *GetAppConnectionPolicyRequest) {
	p := proto.Clone(in).(*GetAppConnectionPolicyRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetAppConnectionPolicyRequest. Required by controller-gen.
func (in *GetAppConnectionPolicyRequest) DeepCopy() *GetAppConnectionPolicyRequest {
	if in == nil {
		return nil
	}
	out := new(GetAppConnectionPolicyRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetAppConnectionPolicyRequest. Required by controller-gen.
func (in *GetAppConnectionPolicyRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetAppConnectionPolicyResponse within kubernetes types, where deepcopy-gen is used.
func (in *GetAppConnectionPolicyResponse) DeepCopyInto(out *GetAppConnectionPolicyResponse) {
	p := proto.Clone(in).(*GetAppConnectionPolicyResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetAppConnectionPolicyResponse. Required by controller-gen.
func (in *GetAppConnectionPolicyResponse) DeepCopy() *GetAppConnectionPolicyResponse {
	if in == nil {
		return nil
	}
	out := new(GetAppConnectionPolicyResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetAppConnectionPolicyResponse. Required by controller-gen.
func (in *GetAppConnectionPolicyResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DeleteAppConnectionPolicyRequest within kubernetes types, where deepcopy-gen is used.
func (in *DeleteAppConnectionPolicyRequest) DeepCopyInto(out *DeleteAppConnectionPolicyRequest) {
	p := proto.Clone(in).(*DeleteAppConnectionPolicyRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteAppConnectionPolicyRequest. Required by controller-gen.
func (in *DeleteAppConnectionPolicyRequest) DeepCopy() *DeleteAppConnectionPolicyRequest {
	if in == nil {
		return nil
	}
	out := new(DeleteAppConnectionPolicyRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DeleteAppConnectionPolicyRequest. Required by controller-gen.
func (in *DeleteAppConnectionPolicyRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DeleteAppConnectionPolicyResponse within kubernetes types, where deepcopy-gen is used.
func (in *DeleteAppConnectionPolicyResponse) DeepCopyInto(out *DeleteAppConnectionPolicyResponse) {
	p := proto.Clone(in).(*DeleteAppConnectionPolicyResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteAppConnectionPolicyResponse. Required by controller-gen.
func (in *DeleteAppConnectionPolicyResponse) DeepCopy() *DeleteAppConnectionPolicyResponse {
	if in == nil {
		return nil
	}
	out := new(DeleteAppConnectionPolicyResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DeleteAppConnectionPolicyResponse. Required by controller-gen.
func (in *DeleteAppConnectionPolicyResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ListAppConnectionPoliciesRequest within kubernetes types, where deepcopy-gen is used.
func (in *ListAppConnectionPoliciesRequest) DeepCopyInto(out *ListAppConnectionPoliciesRequest) {
	p := proto.Clone(in).(*ListAppConnectionPoliciesRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListAppConnectionPoliciesRequest. Required by controller-gen.
func (in *ListAppConnectionPoliciesRequest) DeepCopy() *ListAppConnectionPoliciesRequest {
	if in == nil {
		return nil
	}
	out := new(ListAppConnectionPoliciesRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ListAppConnectionPoliciesRequest. Required by controller-gen.
func (in *ListAppConnectionPoliciesRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ListAppConnectionPoliciesResponse within kubernetes types, where deepcopy-gen is used.
func (in *ListAppConnectionPoliciesResponse) DeepCopyInto(out *ListAppConnectionPoliciesResponse) {
	p := proto.Clone(in).(*ListAppConnectionPoliciesResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListAppConnectionPoliciesResponse. Required by controller-gen.
func (in *ListAppConnectionPoliciesResponse) DeepCopy() *ListAppConnectionPoliciesResponse {
	if in == nil {
		return nil
	}
	out := new(ListAppConnectionPoliciesResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ListAppConnectionPoliciesResponse. Required by controller-gen.
func (in *ListAppConnectionPoliciesResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
