// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package awi

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using ConnectionRequest within kubernetes types, where deepcopy-gen is used.
func (in *ConnectionRequest) DeepCopyInto(out *ConnectionRequest) {
	p := proto.Clone(in).(*ConnectionRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionRequest. Required by controller-gen.
func (in *ConnectionRequest) DeepCopy() *ConnectionRequest {
	if in == nil {
		return nil
	}
	out := new(ConnectionRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionRequest. Required by controller-gen.
func (in *ConnectionRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ConnectionResponse within kubernetes types, where deepcopy-gen is used.
func (in *ConnectionResponse) DeepCopyInto(out *ConnectionResponse) {
	p := proto.Clone(in).(*ConnectionResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionResponse. Required by controller-gen.
func (in *ConnectionResponse) DeepCopy() *ConnectionResponse {
	if in == nil {
		return nil
	}
	out := new(ConnectionResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionResponse. Required by controller-gen.
func (in *ConnectionResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using NetworkDomainConnectionConfig within kubernetes types, where deepcopy-gen is used.
func (in *NetworkDomainConnectionConfig) DeepCopyInto(out *NetworkDomainConnectionConfig) {
	p := proto.Clone(in).(*NetworkDomainConnectionConfig)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDomainConnectionConfig. Required by controller-gen.
func (in *NetworkDomainConnectionConfig) DeepCopy() *NetworkDomainConnectionConfig {
	if in == nil {
		return nil
	}
	out := new(NetworkDomainConnectionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDomainConnectionConfig. Required by controller-gen.
func (in *NetworkDomainConnectionConfig) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using NetworkDomainConnectionConfig_Source within kubernetes types, where deepcopy-gen is used.
func (in *NetworkDomainConnectionConfig_Source) DeepCopyInto(out *NetworkDomainConnectionConfig_Source) {
	p := proto.Clone(in).(*NetworkDomainConnectionConfig_Source)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDomainConnectionConfig_Source. Required by controller-gen.
func (in *NetworkDomainConnectionConfig_Source) DeepCopy() *NetworkDomainConnectionConfig_Source {
	if in == nil {
		return nil
	}
	out := new(NetworkDomainConnectionConfig_Source)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDomainConnectionConfig_Source. Required by controller-gen.
func (in *NetworkDomainConnectionConfig_Source) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using NetworkDomainConnectionConfig_Destination within kubernetes types, where deepcopy-gen is used.
func (in *NetworkDomainConnectionConfig_Destination) DeepCopyInto(out *NetworkDomainConnectionConfig_Destination) {
	p := proto.Clone(in).(*NetworkDomainConnectionConfig_Destination)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDomainConnectionConfig_Destination. Required by controller-gen.
func (in *NetworkDomainConnectionConfig_Destination) DeepCopy() *NetworkDomainConnectionConfig_Destination {
	if in == nil {
		return nil
	}
	out := new(NetworkDomainConnectionConfig_Destination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDomainConnectionConfig_Destination. Required by controller-gen.
func (in *NetworkDomainConnectionConfig_Destination) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using NetworkDomainConnectionConfig_Metadata within kubernetes types, where deepcopy-gen is used.
func (in *NetworkDomainConnectionConfig_Metadata) DeepCopyInto(out *NetworkDomainConnectionConfig_Metadata) {
	p := proto.Clone(in).(*NetworkDomainConnectionConfig_Metadata)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDomainConnectionConfig_Metadata. Required by controller-gen.
func (in *NetworkDomainConnectionConfig_Metadata) DeepCopy() *NetworkDomainConnectionConfig_Metadata {
	if in == nil {
		return nil
	}
	out := new(NetworkDomainConnectionConfig_Metadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDomainConnectionConfig_Metadata. Required by controller-gen.
func (in *NetworkDomainConnectionConfig_Metadata) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using NetworkDomainConnectionConfig_NetworkDomain within kubernetes types, where deepcopy-gen is used.
func (in *NetworkDomainConnectionConfig_NetworkDomain) DeepCopyInto(out *NetworkDomainConnectionConfig_NetworkDomain) {
	p := proto.Clone(in).(*NetworkDomainConnectionConfig_NetworkDomain)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDomainConnectionConfig_NetworkDomain. Required by controller-gen.
func (in *NetworkDomainConnectionConfig_NetworkDomain) DeepCopy() *NetworkDomainConnectionConfig_NetworkDomain {
	if in == nil {
		return nil
	}
	out := new(NetworkDomainConnectionConfig_NetworkDomain)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDomainConnectionConfig_NetworkDomain. Required by controller-gen.
func (in *NetworkDomainConnectionConfig_NetworkDomain) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using NetworkDomainConnectionConfig_NetworkPolicySelector within kubernetes types, where deepcopy-gen is used.
func (in *NetworkDomainConnectionConfig_NetworkPolicySelector) DeepCopyInto(out *NetworkDomainConnectionConfig_NetworkPolicySelector) {
	p := proto.Clone(in).(*NetworkDomainConnectionConfig_NetworkPolicySelector)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDomainConnectionConfig_NetworkPolicySelector. Required by controller-gen.
func (in *NetworkDomainConnectionConfig_NetworkPolicySelector) DeepCopy() *NetworkDomainConnectionConfig_NetworkPolicySelector {
	if in == nil {
		return nil
	}
	out := new(NetworkDomainConnectionConfig_NetworkPolicySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDomainConnectionConfig_NetworkPolicySelector. Required by controller-gen.
func (in *NetworkDomainConnectionConfig_NetworkPolicySelector) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using NetworkDomainConnectionConfig_SecurityPolicySelector within kubernetes types, where deepcopy-gen is used.
func (in *NetworkDomainConnectionConfig_SecurityPolicySelector) DeepCopyInto(out *NetworkDomainConnectionConfig_SecurityPolicySelector) {
	p := proto.Clone(in).(*NetworkDomainConnectionConfig_SecurityPolicySelector)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDomainConnectionConfig_SecurityPolicySelector. Required by controller-gen.
func (in *NetworkDomainConnectionConfig_SecurityPolicySelector) DeepCopy() *NetworkDomainConnectionConfig_SecurityPolicySelector {
	if in == nil {
		return nil
	}
	out := new(NetworkDomainConnectionConfig_SecurityPolicySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDomainConnectionConfig_SecurityPolicySelector. Required by controller-gen.
func (in *NetworkDomainConnectionConfig_SecurityPolicySelector) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using NetworkDomainConnectionConfig_ObservabilityPolicySelector within kubernetes types, where deepcopy-gen is used.
func (in *NetworkDomainConnectionConfig_ObservabilityPolicySelector) DeepCopyInto(out *NetworkDomainConnectionConfig_ObservabilityPolicySelector) {
	p := proto.Clone(in).(*NetworkDomainConnectionConfig_ObservabilityPolicySelector)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDomainConnectionConfig_ObservabilityPolicySelector. Required by controller-gen.
func (in *NetworkDomainConnectionConfig_ObservabilityPolicySelector) DeepCopy() *NetworkDomainConnectionConfig_ObservabilityPolicySelector {
	if in == nil {
		return nil
	}
	out := new(NetworkDomainConnectionConfig_ObservabilityPolicySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDomainConnectionConfig_ObservabilityPolicySelector. Required by controller-gen.
func (in *NetworkDomainConnectionConfig_ObservabilityPolicySelector) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using NetworkDomainConnectionConfig_CostPolicySelector within kubernetes types, where deepcopy-gen is used.
func (in *NetworkDomainConnectionConfig_CostPolicySelector) DeepCopyInto(out *NetworkDomainConnectionConfig_CostPolicySelector) {
	p := proto.Clone(in).(*NetworkDomainConnectionConfig_CostPolicySelector)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDomainConnectionConfig_CostPolicySelector. Required by controller-gen.
func (in *NetworkDomainConnectionConfig_CostPolicySelector) DeepCopy() *NetworkDomainConnectionConfig_CostPolicySelector {
	if in == nil {
		return nil
	}
	out := new(NetworkDomainConnectionConfig_CostPolicySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDomainConnectionConfig_CostPolicySelector. Required by controller-gen.
func (in *NetworkDomainConnectionConfig_CostPolicySelector) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using NetworkDomainConnectionConfig_InspectionPolicySelector within kubernetes types, where deepcopy-gen is used.
func (in *NetworkDomainConnectionConfig_InspectionPolicySelector) DeepCopyInto(out *NetworkDomainConnectionConfig_InspectionPolicySelector) {
	p := proto.Clone(in).(*NetworkDomainConnectionConfig_InspectionPolicySelector)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDomainConnectionConfig_InspectionPolicySelector. Required by controller-gen.
func (in *NetworkDomainConnectionConfig_InspectionPolicySelector) DeepCopy() *NetworkDomainConnectionConfig_InspectionPolicySelector {
	if in == nil {
		return nil
	}
	out := new(NetworkDomainConnectionConfig_InspectionPolicySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDomainConnectionConfig_InspectionPolicySelector. Required by controller-gen.
func (in *NetworkDomainConnectionConfig_InspectionPolicySelector) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using NetworkDomainConnectionConfig_AppConnectionPolicySelector within kubernetes types, where deepcopy-gen is used.
func (in *NetworkDomainConnectionConfig_AppConnectionPolicySelector) DeepCopyInto(out *NetworkDomainConnectionConfig_AppConnectionPolicySelector) {
	p := proto.Clone(in).(*NetworkDomainConnectionConfig_AppConnectionPolicySelector)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDomainConnectionConfig_AppConnectionPolicySelector. Required by controller-gen.
func (in *NetworkDomainConnectionConfig_AppConnectionPolicySelector) DeepCopy() *NetworkDomainConnectionConfig_AppConnectionPolicySelector {
	if in == nil {
		return nil
	}
	out := new(NetworkDomainConnectionConfig_AppConnectionPolicySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDomainConnectionConfig_AppConnectionPolicySelector. Required by controller-gen.
func (in *NetworkDomainConnectionConfig_AppConnectionPolicySelector) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using NetworkDomainConnectionConfig_AccessPolicySelector within kubernetes types, where deepcopy-gen is used.
func (in *NetworkDomainConnectionConfig_AccessPolicySelector) DeepCopyInto(out *NetworkDomainConnectionConfig_AccessPolicySelector) {
	p := proto.Clone(in).(*NetworkDomainConnectionConfig_AccessPolicySelector)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDomainConnectionConfig_AccessPolicySelector. Required by controller-gen.
func (in *NetworkDomainConnectionConfig_AccessPolicySelector) DeepCopy() *NetworkDomainConnectionConfig_AccessPolicySelector {
	if in == nil {
		return nil
	}
	out := new(NetworkDomainConnectionConfig_AccessPolicySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDomainConnectionConfig_AccessPolicySelector. Required by controller-gen.
func (in *NetworkDomainConnectionConfig_AccessPolicySelector) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using NetworkDomainConnectionConfig_Selector within kubernetes types, where deepcopy-gen is used.
func (in *NetworkDomainConnectionConfig_Selector) DeepCopyInto(out *NetworkDomainConnectionConfig_Selector) {
	p := proto.Clone(in).(*NetworkDomainConnectionConfig_Selector)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDomainConnectionConfig_Selector. Required by controller-gen.
func (in *NetworkDomainConnectionConfig_Selector) DeepCopy() *NetworkDomainConnectionConfig_Selector {
	if in == nil {
		return nil
	}
	out := new(NetworkDomainConnectionConfig_Selector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDomainConnectionConfig_Selector. Required by controller-gen.
func (in *NetworkDomainConnectionConfig_Selector) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using NetworkDomainConnectionConfig_MatchName within kubernetes types, where deepcopy-gen is used.
func (in *NetworkDomainConnectionConfig_MatchName) DeepCopyInto(out *NetworkDomainConnectionConfig_MatchName) {
	p := proto.Clone(in).(*NetworkDomainConnectionConfig_MatchName)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDomainConnectionConfig_MatchName. Required by controller-gen.
func (in *NetworkDomainConnectionConfig_MatchName) DeepCopy() *NetworkDomainConnectionConfig_MatchName {
	if in == nil {
		return nil
	}
	out := new(NetworkDomainConnectionConfig_MatchName)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDomainConnectionConfig_MatchName. Required by controller-gen.
func (in *NetworkDomainConnectionConfig_MatchName) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using NetworkDomainConnectionConfig_MatchId within kubernetes types, where deepcopy-gen is used.
func (in *NetworkDomainConnectionConfig_MatchId) DeepCopyInto(out *NetworkDomainConnectionConfig_MatchId) {
	p := proto.Clone(in).(*NetworkDomainConnectionConfig_MatchId)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDomainConnectionConfig_MatchId. Required by controller-gen.
func (in *NetworkDomainConnectionConfig_MatchId) DeepCopy() *NetworkDomainConnectionConfig_MatchId {
	if in == nil {
		return nil
	}
	out := new(NetworkDomainConnectionConfig_MatchId)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDomainConnectionConfig_MatchId. Required by controller-gen.
func (in *NetworkDomainConnectionConfig_MatchId) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using NetworkDomainConnectionConfig_MatchSite within kubernetes types, where deepcopy-gen is used.
func (in *NetworkDomainConnectionConfig_MatchSite) DeepCopyInto(out *NetworkDomainConnectionConfig_MatchSite) {
	p := proto.Clone(in).(*NetworkDomainConnectionConfig_MatchSite)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDomainConnectionConfig_MatchSite. Required by controller-gen.
func (in *NetworkDomainConnectionConfig_MatchSite) DeepCopy() *NetworkDomainConnectionConfig_MatchSite {
	if in == nil {
		return nil
	}
	out := new(NetworkDomainConnectionConfig_MatchSite)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDomainConnectionConfig_MatchSite. Required by controller-gen.
func (in *NetworkDomainConnectionConfig_MatchSite) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ConnectionMetadata within kubernetes types, where deepcopy-gen is used.
func (in *ConnectionMetadata) DeepCopyInto(out *ConnectionMetadata) {
	p := proto.Clone(in).(*ConnectionMetadata)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionMetadata. Required by controller-gen.
func (in *ConnectionMetadata) DeepCopy() *ConnectionMetadata {
	if in == nil {
		return nil
	}
	out := new(ConnectionMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionMetadata. Required by controller-gen.
func (in *ConnectionMetadata) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DisconnectRequest within kubernetes types, where deepcopy-gen is used.
func (in *DisconnectRequest) DeepCopyInto(out *DisconnectRequest) {
	p := proto.Clone(in).(*DisconnectRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisconnectRequest. Required by controller-gen.
func (in *DisconnectRequest) DeepCopy() *DisconnectRequest {
	if in == nil {
		return nil
	}
	out := new(DisconnectRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DisconnectRequest. Required by controller-gen.
func (in *DisconnectRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DisconnectResponse within kubernetes types, where deepcopy-gen is used.
func (in *DisconnectResponse) DeepCopyInto(out *DisconnectResponse) {
	p := proto.Clone(in).(*DisconnectResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisconnectResponse. Required by controller-gen.
func (in *DisconnectResponse) DeepCopy() *DisconnectResponse {
	if in == nil {
		return nil
	}
	out := new(DisconnectResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DisconnectResponse. Required by controller-gen.
func (in *DisconnectResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetConnectionRequest within kubernetes types, where deepcopy-gen is used.
func (in *GetConnectionRequest) DeepCopyInto(out *GetConnectionRequest) {
	p := proto.Clone(in).(*GetConnectionRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetConnectionRequest. Required by controller-gen.
func (in *GetConnectionRequest) DeepCopy() *GetConnectionRequest {
	if in == nil {
		return nil
	}
	out := new(GetConnectionRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetConnectionRequest. Required by controller-gen.
func (in *GetConnectionRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ListConnectionsRequest within kubernetes types, where deepcopy-gen is used.
func (in *ListConnectionsRequest) DeepCopyInto(out *ListConnectionsRequest) {
	p := proto.Clone(in).(*ListConnectionsRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListConnectionsRequest. Required by controller-gen.
func (in *ListConnectionsRequest) DeepCopy() *ListConnectionsRequest {
	if in == nil {
		return nil
	}
	out := new(ListConnectionsRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ListConnectionsRequest. Required by controller-gen.
func (in *ListConnectionsRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ListConnectionsResponse within kubernetes types, where deepcopy-gen is used.
func (in *ListConnectionsResponse) DeepCopyInto(out *ListConnectionsResponse) {
	p := proto.Clone(in).(*ListConnectionsResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListConnectionsResponse. Required by controller-gen.
func (in *ListConnectionsResponse) DeepCopy() *ListConnectionsResponse {
	if in == nil {
		return nil
	}
	out := new(ListConnectionsResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ListConnectionsResponse. Required by controller-gen.
func (in *ListConnectionsResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ConnectionStatusRequest within kubernetes types, where deepcopy-gen is used.
func (in *ConnectionStatusRequest) DeepCopyInto(out *ConnectionStatusRequest) {
	p := proto.Clone(in).(*ConnectionStatusRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionStatusRequest. Required by controller-gen.
func (in *ConnectionStatusRequest) DeepCopy() *ConnectionStatusRequest {
	if in == nil {
		return nil
	}
	out := new(ConnectionStatusRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionStatusRequest. Required by controller-gen.
func (in *ConnectionStatusRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ConnectionStatusResponse within kubernetes types, where deepcopy-gen is used.
func (in *ConnectionStatusResponse) DeepCopyInto(out *ConnectionStatusResponse) {
	p := proto.Clone(in).(*ConnectionStatusResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionStatusResponse. Required by controller-gen.
func (in *ConnectionStatusResponse) DeepCopy() *ConnectionStatusResponse {
	if in == nil {
		return nil
	}
	out := new(ConnectionStatusResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionStatusResponse. Required by controller-gen.
func (in *ConnectionStatusResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ConnectionInformation within kubernetes types, where deepcopy-gen is used.
func (in *ConnectionInformation) DeepCopyInto(out *ConnectionInformation) {
	p := proto.Clone(in).(*ConnectionInformation)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionInformation. Required by controller-gen.
func (in *ConnectionInformation) DeepCopy() *ConnectionInformation {
	if in == nil {
		return nil
	}
	out := new(ConnectionInformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionInformation. Required by controller-gen.
func (in *ConnectionInformation) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
