// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.2
// source: sla.proto

package awi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Hard_SLA struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// +kubebuilder:validation:Optional
	Bandwidth uint32 `protobuf:"varint,1,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	// +kubebuilder:validation:Optional
	Jitter uint32 `protobuf:"varint,2,opt,name=jitter,proto3" json:"jitter,omitempty"`
	// +kubebuilder:validation:Optional
	Latency uint32 `protobuf:"varint,3,opt,name=latency,proto3" json:"latency,omitempty"`
	// +kubebuilder:validation:Optional
	Loss float64 `protobuf:"fixed64,4,opt,name=loss,proto3" json:"loss,omitempty"`
}

func (x *Hard_SLA) Reset() {
	*x = Hard_SLA{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sla_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hard_SLA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hard_SLA) ProtoMessage() {}

func (x *Hard_SLA) ProtoReflect() protoreflect.Message {
	mi := &file_sla_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hard_SLA.ProtoReflect.Descriptor instead.
func (*Hard_SLA) Descriptor() ([]byte, []int) {
	return file_sla_proto_rawDescGZIP(), []int{0}
}

func (x *Hard_SLA) GetBandwidth() uint32 {
	if x != nil {
		return x.Bandwidth
	}
	return 0
}

func (x *Hard_SLA) GetJitter() uint32 {
	if x != nil {
		return x.Jitter
	}
	return 0
}

func (x *Hard_SLA) GetLatency() uint32 {
	if x != nil {
		return x.Latency
	}
	return 0
}

func (x *Hard_SLA) GetLoss() float64 {
	if x != nil {
		return x.Loss
	}
	return 0
}

type Soft_SLA struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrafficProfile string `protobuf:"bytes,1,opt,name=traffic_profile,json=trafficProfile,proto3" json:"traffic_profile,omitempty"`
	Priority       string `protobuf:"bytes,2,opt,name=priority,proto3" json:"priority,omitempty"`
}

func (x *Soft_SLA) Reset() {
	*x = Soft_SLA{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sla_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Soft_SLA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Soft_SLA) ProtoMessage() {}

func (x *Soft_SLA) ProtoReflect() protoreflect.Message {
	mi := &file_sla_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Soft_SLA.ProtoReflect.Descriptor instead.
func (*Soft_SLA) Descriptor() ([]byte, []int) {
	return file_sla_proto_rawDescGZIP(), []int{1}
}

func (x *Soft_SLA) GetTrafficProfile() string {
	if x != nil {
		return x.TrafficProfile
	}
	return ""
}

func (x *Soft_SLA) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

type Network_SLA struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hard *Hard_SLA `protobuf:"bytes,1,opt,name=hard,proto3" json:"hard,omitempty"`
	Soft *Soft_SLA `protobuf:"bytes,2,opt,name=soft,proto3" json:"soft,omitempty"`
}

func (x *Network_SLA) Reset() {
	*x = Network_SLA{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sla_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Network_SLA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Network_SLA) ProtoMessage() {}

func (x *Network_SLA) ProtoReflect() protoreflect.Message {
	mi := &file_sla_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Network_SLA.ProtoReflect.Descriptor instead.
func (*Network_SLA) Descriptor() ([]byte, []int) {
	return file_sla_proto_rawDescGZIP(), []int{2}
}

func (x *Network_SLA) GetHard() *Hard_SLA {
	if x != nil {
		return x.Hard
	}
	return nil
}

func (x *Network_SLA) GetSoft() *Soft_SLA {
	if x != nil {
		return x.Soft
	}
	return nil
}

type SLAResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SupportsHardNetworkSla  bool      `protobuf:"varint,1,opt,name=supports_hard_network_sla,json=supportsHardNetworkSla,proto3" json:"supports_hard_network_sla,omitempty"`
	SupportsSoftNetworkSla  bool      `protobuf:"varint,2,opt,name=supports_soft_network_sla,json=supportsSoftNetworkSla,proto3" json:"supports_soft_network_sla,omitempty"`
	AvailableHardNetworkSla *Hard_SLA `protobuf:"bytes,3,opt,name=available_hard_network_sla,json=availableHardNetworkSla,proto3" json:"available_hard_network_sla,omitempty"`
	MeetsSla                bool      `protobuf:"varint,4,opt,name=meets_sla,json=meetsSla,proto3" json:"meets_sla,omitempty"`
}

func (x *SLAResponse) Reset() {
	*x = SLAResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sla_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SLAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SLAResponse) ProtoMessage() {}

func (x *SLAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sla_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SLAResponse.ProtoReflect.Descriptor instead.
func (*SLAResponse) Descriptor() ([]byte, []int) {
	return file_sla_proto_rawDescGZIP(), []int{3}
}

func (x *SLAResponse) GetSupportsHardNetworkSla() bool {
	if x != nil {
		return x.SupportsHardNetworkSla
	}
	return false
}

func (x *SLAResponse) GetSupportsSoftNetworkSla() bool {
	if x != nil {
		return x.SupportsSoftNetworkSla
	}
	return false
}

func (x *SLAResponse) GetAvailableHardNetworkSla() *Hard_SLA {
	if x != nil {
		return x.AvailableHardNetworkSla
	}
	return nil
}

func (x *SLAResponse) GetMeetsSla() bool {
	if x != nil {
		return x.MeetsSla
	}
	return false
}

var File_sla_proto protoreflect.FileDescriptor

var file_sla_proto_rawDesc = []byte{
	0x0a, 0x09, 0x73, 0x6c, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6e, 0x0a, 0x08, 0x48,
	0x61, 0x72, 0x64, 0x5f, 0x53, 0x4c, 0x41, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x61, 0x6e, 0x64, 0x77,
	0x69, 0x64, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x62, 0x61, 0x6e, 0x64,
	0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x6a, 0x69, 0x74, 0x74, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6a, 0x69, 0x74, 0x74, 0x65, 0x72, 0x12, 0x18, 0x0a,
	0x07, 0x6c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07,
	0x6c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6f, 0x73, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x6c, 0x6f, 0x73, 0x73, 0x22, 0x4f, 0x0a, 0x08, 0x53,
	0x6f, 0x66, 0x74, 0x5f, 0x53, 0x4c, 0x41, 0x12, 0x27, 0x0a, 0x0f, 0x74, 0x72, 0x61, 0x66, 0x66,
	0x69, 0x63, 0x5f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x74, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x22, 0x4b, 0x0a, 0x0b,
	0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x53, 0x4c, 0x41, 0x12, 0x1d, 0x0a, 0x04, 0x68,
	0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x48, 0x61, 0x72, 0x64,
	0x5f, 0x53, 0x4c, 0x41, 0x52, 0x04, 0x68, 0x61, 0x72, 0x64, 0x12, 0x1d, 0x0a, 0x04, 0x73, 0x6f,
	0x66, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x53, 0x6f, 0x66, 0x74, 0x5f,
	0x53, 0x4c, 0x41, 0x52, 0x04, 0x73, 0x6f, 0x66, 0x74, 0x22, 0xe8, 0x01, 0x0a, 0x0b, 0x53, 0x4c,
	0x41, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x19, 0x73, 0x75, 0x70,
	0x70, 0x6f, 0x72, 0x74, 0x73, 0x5f, 0x68, 0x61, 0x72, 0x64, 0x5f, 0x6e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x5f, 0x73, 0x6c, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x16, 0x73, 0x75,
	0x70, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x48, 0x61, 0x72, 0x64, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x53, 0x6c, 0x61, 0x12, 0x39, 0x0a, 0x19, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x73,
	0x5f, 0x73, 0x6f, 0x66, 0x74, 0x5f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x73, 0x6c,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x16, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74,
	0x73, 0x53, 0x6f, 0x66, 0x74, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x53, 0x6c, 0x61, 0x12,
	0x46, 0x0a, 0x1a, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x68, 0x61, 0x72,
	0x64, 0x5f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x73, 0x6c, 0x61, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x48, 0x61, 0x72, 0x64, 0x5f, 0x53, 0x4c, 0x41, 0x52, 0x17,
	0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x48, 0x61, 0x72, 0x64, 0x4e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x53, 0x6c, 0x61, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x65, 0x65, 0x74, 0x73,
	0x5f, 0x73, 0x6c, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x6d, 0x65, 0x65, 0x74,
	0x73, 0x53, 0x6c, 0x61, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x3b, 0x61, 0x77, 0x69, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sla_proto_rawDescOnce sync.Once
	file_sla_proto_rawDescData = file_sla_proto_rawDesc
)

func file_sla_proto_rawDescGZIP() []byte {
	file_sla_proto_rawDescOnce.Do(func() {
		file_sla_proto_rawDescData = protoimpl.X.CompressGZIP(file_sla_proto_rawDescData)
	})
	return file_sla_proto_rawDescData
}

var file_sla_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_sla_proto_goTypes = []interface{}{
	(*Hard_SLA)(nil),    // 0: Hard_SLA
	(*Soft_SLA)(nil),    // 1: Soft_SLA
	(*Network_SLA)(nil), // 2: Network_SLA
	(*SLAResponse)(nil), // 3: SLAResponse
}
var file_sla_proto_depIdxs = []int32{
	0, // 0: Network_SLA.hard:type_name -> Hard_SLA
	1, // 1: Network_SLA.soft:type_name -> Soft_SLA
	0, // 2: SLAResponse.available_hard_network_sla:type_name -> Hard_SLA
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sla_proto_init() }
func file_sla_proto_init() {
	if File_sla_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sla_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hard_SLA); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sla_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Soft_SLA); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sla_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Network_SLA); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sla_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SLAResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sla_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sla_proto_goTypes,
		DependencyIndexes: file_sla_proto_depIdxs,
		MessageInfos:      file_sla_proto_msgTypes,
	}.Build()
	File_sla_proto = out.File
	file_sla_proto_rawDesc = nil
	file_sla_proto_goTypes = nil
	file_sla_proto_depIdxs = nil
}
