# Copyright (c) 2023 Cisco Systems, Inc. and its affiliates
# All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http:www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: awi.app-net-interface.io/v1alpha
kind: SecurityPolicy #A network domain could be a VPC or VRF. Exists behind a router.
metadata:
  name: "Network security policy"
  namespace: ""
spec:
  metadata:
    name: "abcd@cisco.com"
    description: ""
    creationTimestamp: "2023-08-15T12:34:56Z"
    modificationTimestamp: "2023-08-15T13:45:67Z"
    label: 
      key: "value"
  securityPolicies: #One or more policies can be attached.
    accessPolicy: #Secure Access 
      selector:
        - matchLabels:
          key: "value"
        - matchId:
          id: ""
        - matchName:
          key: "value"
    inspectionPolicy: #Secure Traffic
      allowInspection: true   # Should this flow be inspected.
      redirectTraffic: true   #Specify inline inspection or third party 
      selector:
        - matchLabels:
          key: "value"
        - matchId:
          id: ""
        - matchName:
          key: "value"
    geoFencingPolicy: #Limit access 
      selector:
        - matchLabels:
          key: "value"
        - matchId:
          id: ""
        - matchName:
          key: "value"
    privacyPolicy:    # Privacy
      selector:
        - matchLabels:
          key: "value"
        - matchId:
          id: ""
        - matchName:
          key: "value"